### ISSUE TITLE
Não Roda

### ISSUE THREAD

**Issue by CharlesQueiroz** [TechMinds-Group/TaskFlow#13]
Tentei baixar o projeto e seguir o readme, mas nao funciona. 

Estou usando um MAC M2, 64GB RAM e 2TB disco. 

<img width="1728" alt="Screenshot 2023-07-10 at 15 33 46" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/5fb3ff33-ed8f-4e75-8697-81d64f7da240">

comando com problema: `flask create_database`

**Comment by feiticeiro-tec** [comment]
`pip install -r requirements.txt`

**Comment by CharlesQueiroz** [comment]
Eu tinha feito isso. Nao funcionou. 
<img width="1722" alt="Screenshot 2023-07-10 at 16 03 59" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/f01d6837-a952-4d0c-a2f6-babff51413a0">

**Comment by Igorsaulo** [comment]
Use:
python -m venv meu_mabiente_virtual

No lugar de:
virtualenv meu_ambiente_virtual

**Comment by CharlesQueiroz** [comment]
Mesmo problema. 

Segue as evidencias: 
<img width="923" alt="Screenshot 2023-07-10 at 18 16 01" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/591b1715-2659-421a-979e-e7303404ab16">
<img width="857" alt="Screenshot 2023-07-10 at 18 16 30" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/31759591-68e2-48d1-9fb1-c720035335e0">
<img width="1726" alt="Screenshot 2023-07-10 at 18 16 43" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/c4e12d7c-bd53-476f-8ea6-ad0b07ea9c06">

Recriei um env novo, com um novo nome.. instalei as dependencias, mas não resolveu.

**Comment by Igorsaulo** [comment]
Seu usuario não tem permissão para executar o programa use o seguinte comando no terminal para resolver:

chown -R username TaskFlow

**Comment by CharlesQueiroz** [comment]
Excelente !! Agora resolveu. Muito obrigado. 

<img width="1714" alt="Screenshot 2023-07-10 at 19 09 05" src="https://github.com/TechMinds-Group/TaskFlow/assets/2192264/b0eff8fd-15ef-41f0-aea4-fa409f44022a">
